### ISSUE TITLE
Can you share me the Yaesu packet format Mic-E decode methord?

### ISSUE THREAD

**Issue by bi7jta** [jamescarlson/FreeAPRS#1]
hi: 
   I found the code not include, can you share me the Yaesu packet format Mic-E decode methord?
thanks!
      de bi7jta ,CN Shenzhen, 73!

**Comment by jamescarlson** [comment]
Luckily I did not have to write the vast majority of the parsing code. Taking a look at the APRS specification (APRS101.pdf), one can get easily overwhelmed with every little addition to the spec that made it in.

I'm using a C port of the Finnish APRS Parser (you can find more information [here](http://www.pakettiradio.net/libfap/))

The relevant method should be around [here](https://github.com/jamescarlson/FreeAPRS/blob/master/Modulator/helpers.c#L311)

**Comment by bi7jta** [comment]
Thanks Very Much！Very helpful for me,i will debug MIC-E packet.
